#=========================================================================
# Synopsys VCS -- SDF Simulation Arguments
#=========================================================================

name: synopsys-vcs-sdf

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design.sdf

outputs:
  - sdf_args.txt

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - echo "-sdf max:$design_name:design.sdf +sdfverbose +overlap +multisource_int_delays +neg_tchk -negdelay" > outputs/sdf_args.txt

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
